/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chic;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Toy
 */
public class chico_chica extends javax.swing.JFrame {

    /**
     * Creates new form chico_chica
     */
    public chico_chica() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    ///Metodos para cambiar de imagen 
   public void imagenChico(){
       
       ImageIcon chico;
       chico = new ImageIcon(getClass().getResource("/imagenes/chico recorte.png"));
       Icon chicoRecortado = new ImageIcon(chico.getImage().getScaledInstance(
               imagen.getWidth(), imagen.getHeight(), WIDTH)); 
       imagen.setIcon(chicoRecortado);
   }
    public void imagenChica(){
       
       ImageIcon chica;
       chica = new ImageIcon(getClass().getResource("/imagenes/chica recortada.png"));
       Icon chicaRecortada = new ImageIcon(chica.getImage().getScaledInstance(
               imagen.getWidth(), imagen.getHeight(), WIDTH)); 
       imagen.setIcon(chicaRecortada);
   }
     public void imagenChicoConGafas(){
       
       ImageIcon chicoConGafas;
       chicoConGafas = new ImageIcon(getClass().getResource("/imagenes/chico con gafas recortado.png"));
       Icon chicoRecortadoConGafas = new ImageIcon(chicoConGafas.getImage().getScaledInstance(
               imagen.getWidth(), imagen.getHeight(), WIDTH)); 
       imagen.setIcon(chicoRecortadoConGafas);
   }
     public void imagenChicaConGafas(){
       
       ImageIcon chicaConGafas;
       chicaConGafas = new ImageIcon(getClass().getResource("/imagenes/chica con gafas.png"));
       Icon chicaRecortadaConGafas = new ImageIcon(chicaConGafas.getImage().getScaledInstance(
               imagen.getWidth(), imagen.getHeight(), WIDTH)); 
       imagen.setIcon(chicaRecortadaConGafas);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chicosOchicas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Chica = new javax.swing.JRadioButton();
        Chico = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        Gafas = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chicosOchicas.add(Chica);
        Chica.setText("Chica");
        Chica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicaActionPerformed(evt);
            }
        });

        chicosOchicas.add(Chico);
        Chico.setText("Chico");
        Chico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Chico)
                .addGap(18, 18, 18)
                .addComponent(Chica)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chico)
                    .addComponent(Chica))
                .addContainerGap())
        );

        Gafas.setText("Gafas");
        Gafas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GafasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Gafas)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Gafas)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicaActionPerformed
       if(Chica.isSelected()){
            imagenChica();
        }
        if(Gafas.isSelected()){
            imagenChicaConGafas();
        }
    }//GEN-LAST:event_ChicaActionPerformed

    private void ChicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicoActionPerformed
        if(Chico.isSelected()){
            imagenChico();
        }
       if(Gafas.isSelected()){
            imagenChicoConGafas();
        }
    }//GEN-LAST:event_ChicoActionPerformed

    private void GafasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GafasActionPerformed
       if(Gafas.isSelected() && Chico.isSelected()){
            imagenChicoConGafas();
        }
       else if(Gafas.isSelected() && Chica.isSelected()){
           imagenChicaConGafas();
       }
    }//GEN-LAST:event_GafasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chico_chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chico_chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chico_chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chico_chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chico_chica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Chica;
    private javax.swing.JRadioButton Chico;
    private javax.swing.JCheckBox Gafas;
    private javax.swing.ButtonGroup chicosOchicas;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
